### ISSUE TITLE
Python 2.7 linux wheels are broken

### ISSUE THREAD

**Issue by tiran** [al45tair/netifaces#2] opened 2018-02-13 16:28 UTC
The Python 2.7 wheels for Linux are broken and fail to import with ``undefined symbol: PyUnicodeUCS2_FromString``. The ``cp27mu`` should be a wide unicode builds with ``PyUnicodeUCS4_*``, but the extension module uses ``PyUnicodeUCS2_FromString``. This breaks literally any Linux distribution that compiles Python 2.7 with UCS4 (Debian, Fedora, ...).

```
$ virtualenv-2.7 venv
New python executable in /tmp/venv/bin/python2
Also creating executable in /tmp/venv/bin/python
Installing setuptools, pip, wheel...done.
$ venv/bin/pip install netifaces
Collecting netifaces
  Downloading netifaces-0.10.6-cp27-cp27mu-manylinux1_x86_64.whl
Installing collected packages: netifaces
Successfully installed netifaces-0.10.6
$ venv/bin/python
Python 2.7.14 (default, Jan 17 2018, 14:28:32) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import netifaces
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /tmp/venv/lib/python2.7/site-packages/netifaces.so: undefined symbol: ImportError: /tmp/venv/lib/python2.7/site-packages/netifaces.so: undefined symbol: PyUnicodeUCS2_FromString
```

```
$ strings /usr/lib64/libpython2.7.so | egrep PyUnicodeUCS._FromString
PyUnicodeUCS4_FromString
```

**Comment by tiran** [comment] 2018-02-13 16:33
The ABI incompatibility is explained on the manylinux repos https://github.com/pypa/manylinux#docker-images

**Comment by al45tair** [comment] 2018-02-13 16:46
Hmmm. That's odd, because all I do is run through the `/opt/python/*` folders using `pip` to build the wheels [like this](https://github.com/al45tair/netifaces/blob/master/makewheels.sh).

As far as I can tell, that's the same thing that [this script here](https://github.com/pypa/python-manylinux-demo/blob/master/travis/build-wheels.sh) is doing.

Since it's quite clearly broken, I've removed the wheel files in question for now.

**Comment by tiran** [comment] 2018-02-13 16:49
It might not be enough to remove the files. PyPI has them cached. The CDN and mirrors will keep on delivering the packages.

@njsmith @alex @trishankatdatadog please have a look. Is there a problem with latest manylinux builder?

**Comment by trishankatdatadog** [comment] 2018-02-13 16:56
Hmm, interesting, I'm not sure what's going on here. AFAICT, I haven't introduced any changes that should break this, but you never know. @njsmith, what do you think is happening?

**Comment by al45tair** [comment] 2018-02-13 17:15
I just tried building the wheels again and tried installing the wheel that gave the error above in the manylinux1 docker image, and that worked fine. Also, running strings on the netifaces.so file I can see it using the correct UCS4 function:

    [root@97b631efc3fe /]# /opt/python/cp27-cp27mu/bin/pip install /netifaces/wheelhouse/netifaces-0.10.6-cp27-cp27mu-manylinux1_x86_64.whl 
    Processing /netifaces/wheelhouse/netifaces-0.10.6-cp27-cp27mu-manylinux1_x86_64.whl
    Installing collected packages: netifaces
    Successfully installed netifaces-0.10.6
    [root@97b631efc3fe /]# strings /opt/python/cp27-cp27mu/lib/python2.7/site-packages/netifaces.so | grep PyUnicodeUCS
    PyUnicodeUCS4_FromString

I'm beginning to wonder if the problem is nothing to do with the wheel build process, but maybe some bug in twine (which I used to upload the wheels)? Am I crazy to think that?

**Comment by jd** [comment] 2018-02-13 17:46
We're also being hit by this FTR. Would be great to be able to delete the wheel in the meantime I guess, or upload a new version without wheels.

**Comment by al45tair** [comment] 2018-02-13 17:50
@jd The wheels have already been deleted. Hopefully you're not still seeing this behaviour (you might need to clear some cache somewhere?)

**Comment by njsmith** [comment] 2018-02-14 10:57
I'm not aware of any way that the docker image could produce compiled extensions with those symbols. I'm also surprised that auditwheel didn't catch that – I thought it had a check for this...

If you're mounting your source tree directly into the docker image, maybe double check you don't have any stale files in `build/` first...

**Comment by al45tair** [comment] 2018-05-02 09:28
I've just uploaded new wheels; testing the files individually, they seem to work as expected, so I'm closing this.

**Closed by al45tair** 2018-05-02 09:28 UTC
